views/bussiness.py
from flask import Blueprint, render_template, session, redirect, request, url_for, flash
from sqlalchemy import or_
from ..models import  Orders, User
from ..extension import db
from flask_paginate import Pagination, get_page_parameter
import time
from ..zmqpublisher import publisher
from ..blockchain import add_new_block
import threading
import os
import json

_basepath = os.path.abspath(os.path.dirname(__file__))
conf = json.load(open(os.path.abspath(os.path.dirname(__file__))+"/../conf.json"))

buss_page = Blueprint('bussiness_page', __name__)

@buss_page.route('/corderslist')
def list_all_orders(limit=10):
    id = session.get('user_id')
    user = User.query.get(id)
    data = Orders.query.filter(or_(Orders.status=="已出厂", Orders.status=="已生产")).all()
    page = int(request.args.get("page", 1))
    start = (page - 1) * limit
    end = page * limit if len(data) > page * limit else len(data)
    pagination = Pagination(css_framework='bootstrap4', page=page, total=len(data), outer_window=0, inner_window=1)
    ret = Orders.query.filter(or_(Orders.status=="已出厂", Orders.status=="已生产")).slice(start, end)
    return render_template("bussiness/orderslist.html", orders=ret, pagination=pagination, user=user)


@buss_page.route('/corderslist/query', methods=[ 'POST'])
def query():
    id = request.form.get('o_id')
    order = Orders.query.get(id)
    if (order):
        if order.status == "已出厂" or order.status =="已生产":
            return render_template("bussiness/orders_query.html", order=order)
        else:
            return render_template('error_page.html', message="无权限查看")

    else:
        return render_template('error_page.html', message="查询结果不存在")

@buss_page.route('/outc/<id>', methods=['GET', 'POSt'])
def outc(id):
    order = Orders.query.get(id)
    if request.method == 'GET':
        if order.status=="已出厂":
            message = "商品已经出厂，无法出厂"
            return render_template('error_page.html', message=message)
        else:
            return render_template('bussiness/outc.html', order=order)
    else:
        id = request.form.get("id")
        desc =request.form.get("desc")
        tel = request.form.get("tel")
        person = request.form.get("person")
        order = Orders.query.get(id)
        order.desc = desc
        order.tel =tel
        order.person = person
        order.status = "已出厂"
        order.o_time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        if desc == "" or tel == "" or person == "":
            flash('目的地或联系人或联系电话不能为空')
            return render_template('bussiness/outc.html', order=order)
        else:
            db.session.add(order)
            db.session.commit()
            add_new_block("生产商出厂", order.id)
            return redirect(url_for('login_page.users'))

        #return redirect(url_for('login_page.users'))


@buss_page.route('/add', methods=['GET', 'POSt'])
def add():
    if request.method == 'GET':
        return render_template('bussiness/add.html')
    else:
        o_name = request.form.get("o_name")
        location = request.form.get("location")
        o_time  = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        status = "已生产"
        person = "无"
        tel = "无"
        desc = "无"
        comp = "无"
        order = Orders(o_name, o_time, location, person, tel, desc, comp, status )
        if o_name == "" or tel == "" or location == "":
            flash('商品名或目的地不能为空')
            return render_template('bussiness/add.html')

        db.session.add(order)
        db.session.commit()
        add_new_block("生产商生产", order.id)
        return redirect(url_for('login_page.users'))

        #return render_template("bussiness/error_page.html", message="新增成功")

views/login.py
from flask import Blueprint, render_template, session, redirect, request, url_for, flash
from ..models import User, create_data, Orders
from ..extension import db

from ..blockchain import get_all_blocks
from werkzeug.security import check_password_hash, generate_password_hash


login_page = Blueprint('login_page', __name__)


@login_page.route('/login_page')
def users():
    id = session.get('user_id')
    if id:
        user = User.query.get(int(id))
        if user.types== "管理员":
            return redirect(url_for('admin_page.orders'))
        elif user.types == "厂商":
            return redirect(url_for('bussiness_page.list_all_orders'))
        elif user.types == "商家":
            return redirect(url_for('customer_page.list_all_orders'))
        elif user.types == "物流公司":
            return redirect(url_for('logistics_page.list_all_commodities'))
        elif user.types == "仓库":
            return redirect(url_for('warehouse_page.list_all_commodities'))
    else:
        return redirect('/')


@login_page.route('/')
@login_page.route('/login', methods=['GET', 'PoSt'])
def login():
    if request.method == 'GET':
        return render_template('login/login.html')
    else:
        name = request.form.get('name')
        pwd = request.form.get('password')
        if name == "" or pwd == "":
            flash('账号和密码不能为空')
            return render_template('login/login.html')

        user = User.query.filter(User.username == name).first()

        if user and check_password_hash(user.password, pwd):
            session['user_id'] = user.id
            return redirect(url_for('login_page.users'))
        else:
            flash('密码错误')
            return render_template('login/login.html')


@login_page.route('/addinitdata', methods=['GET', 'POST'])
def addinitdata():
    if request.method == 'POST':
        create_data()
        return render_template('login/login.html')


@login_page.route('/user_index/<id>', methods=['GET', 'POST'])
def edit(id):
    user = User.query.get(id)

    if request.method == 'GET':
        return render_template('login/edit.html',user=user)
    else:
        username = request.form.get('username')
        # old_password = request.form.get('old_password')
        # password = request.form.get('new_password')
        gender = request.form.get('gender')
        email = request.form.get('email')

        if not username or not gender or not email:
            flash("Invalid Input")
            return render_template('login/edit.html', user=user)

        user.username = username
        # user.password = generate_password_hash(password)
        user.gender = gender
        user.email = email
        db.session.commit()
        return redirect(url_for('login_page.users'))


@login_page.route('/user_password_index/<id>', methods=['GET', 'POST'])
def password_edit(id):
    user = User.query.get(id)

    if request.method == 'GET':
        return render_template('login/password_edit.html', user=user)
    else:
        # username = request.form.get('username')
        old_password = request.form.get('old_password')
        password = request.form.get('new_password')
        re_password = request.form.get('re_new_password')
        # gender = request.form.get('gender')
        # email = request.form.get('email')

        if not password == re_password:
            flash("新密码输入不同")
            return render_template('login/password_edit.html', user=user)

        if not check_password_hash(user.password, old_password):
            flash("原密码输入错误")
            return render_template('login/password_edit.html', user=user)
        
        # user.username = username
        user.password = generate_password_hash(password)
        # user.gender = gender
        # user.email = email
        db.session.commit()
        return redirect(url_for('login_page.users'))

@login_page.route('/exit', methods=['GET', 'POST'])
def exit():
    return render_template('login/login.html')

@login_page.route('/show_detail/<order_id>')
def show_detail(order_id):
    order = Orders.query.get(order_id)
    block_in_chain = get_all_blocks(order_id)
    if len(block_in_chain) != 0:
        block = block_in_chain[-1]
        message = block.history
        messages = message.split('\n')
        if messages[-1] == "":
            messages = messages[:-1]
    else:
        messages = ""
    return render_template('showdetail.html', order=order, messages=messages)

@login_page.route('/query',methods=['GET', 'POST'])
def query():
    o_id = request.form.get('o_id')
    order = Orders.query.filter(Orders.id==o_id).first()
    id = session.get('user_id')
    if id:
        user = User.query.get(int(id))
        if user.types == "商家":
            if order:
                if order.status == "已发货" or order.status == "已签收":
                    return render_template('customer/orders_query.html', orders=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")

        elif user.types == "物流公司":
            if order:
                if order.status == "已发货" or order.status == "已入仓":
                    return render_template('logistics/logistics_query.html', order=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")


        elif user.types == "仓库":
            if order:
                if order.status == "已出厂" or order.status == "已入仓":
                    return render_template('warehouse/warehouse_query.html', orders=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")

        #return render_template('orders_query.html', order=order)

templates/bussiness/add.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>新增订单</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
</head>
<body class="layui-view-body">
    <div class="layui-content">
    	<!--面包屑导航-->
    	<div class="mianb">
    		<div class="mblf layui-col-xs6 layui-col-md6">
    			 <i class="layui-icon">&#xe656;</i>
    			 <p>物流追踪管理 > <span>生产商</span></p>
    		</div>
    		<div class="mbrt layui-col-xs6 layui-col-md6">
    			<a href="{{url_for('login_page.users')}}" class="layui-btn layui-btn-normal" >返回</a>
    		</div>
    	</div>
    	<!--面包屑导航-->
        <div class="layui-row">
            <div class="layui-card">
            	<div class="table-responsive">
                    <form action="{{ url_for('bussiness_page.add') }}" method="post">
                        <table class="layui-table" lay-skin="line" lay-size="lg" id="table">
                        <tr><td>订单名：</td><td><input  type="text" name="o_name" /></td></tr>
                        <tr><td>产地地：</td><td><input  type="text" name="location" /></td></tr>
                        <tr><td> </td><td><input id="submit" type="submit" name="submit" value="新增" class="layui-btn layui-btn-normal" /></td></tr>
                        </table>
                    </form>
			 	</div>

           		<!--分页-->
           		<div id="page"></div>
           		<!--分页-->
            </div>
        </div>
    </div>
    <font size="3" color="red" align="center">
    {% for message in get_flashed_messages() %}
        <p class="alert">{{ message }}</p>
    {% endfor %}
   	<div>
        <script src="../../static/assets/layui.js"></script>
        <script src="../../static/index.js" data-main="home"></script>
            <script src="../../static/home.js"></script>
    </div>

</body>
</html>

templates/bussiness/commodity_query.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>
    <tr>
        <td>商品名</td>
        <td>价格</td>
    </tr>
    <tr>
        <td>{{ commodity.name }}</td>
        <td>{{ commodity.price }}</td>
    </tr>
</table>
<ur class="sub">
    <li><a class="" href="/commoditylist">
        <span class="sub-menu-text">返回</span>></a>
    </li>
</ur>
</body>
</html>

templates/bussiness/commoditylist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{{url_for('static', filename='jquery.min.js')}}"></script>
    <script>

     function deletecommodity(id)
     {
        $.ajax({
        url:'/commoditylist/delete/' + id,
        dataType: 'html',
        data:id,
        success:function()
        {
            alert("删除成功")
            location.reload(true);
        }
        })
     }
    </script>

</head>
<body>
    <meta charset="UTF-8">
    <title>商品</title>
    <table>
    <tr>
        <td>编号</td>
        <td>商品名</td>
        <td>价格</td>
    </tr>
        {% for commo in commodity %}
    <tr>
        <form action="{{ url_for('bussiness_page.edit') }}" method="post">
            <td><input type="text" name="id" value="{{ commo.id }}" class="form-control" readonly="readonly" ></td>
            <td><input type="text" name="name" value="{{ commo.name }}" class="form-control" placeholder="Text input"></td>
            <td><input type="text" name="price" value="{{ commo.price }}" class="form-control" placeholder="Text input"></td>
            <td>&nbsp;</td><td><input type="submit" name="submit" value="修改" /></td>
        </form>
            <td>
            <button onclick="deletecommodity({{commo.id}})">下架</button>
        </td>

    </tr>
        {% endfor %}
         <tr>
        <td>商品名</td>
        <td>价格</td>
         </tr>
        <tr>
        <form action="{{ url_for('bussiness_page.add') }}" method="post">
            <td><input type="text" name="name"  class="form-control"></td>
            <td><input type="text" name="price"  class="form-control" ></td>
            <td>&nbsp;</td><td><input type="submit" name="submit" value="新增" /></td>
        </form>
        </tr>
    </table>
    <tr>
        <form action="{{ url_for('bussiness_page.query') }}" method="post">
            <td>名称: <input name="name" type="text" value=></td>
            <td><input type="submit" name="submit" value="查询" /></td>
        </form>
    </tr>

</body>
</html>

templates/bussiness/editcommo_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改成功</title>
</head>
<body>
    修改成功
    <ur class="sub">
        <li><a class="" href="/commoditylist">
        <span class="sub-menu-text">返回</span>></a>
        </li>
    </ur>

</body>
</html>

templates/bussiness/error_page.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>厂商</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
  <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<body class="layui-view-body">

  <div class="alert alert-danger alert-dismissible">
    <a type="submit" class="close" href="/corderslist">&times;</a>
    <strong>失败!</strong> {{message}}。
  </div>


   	</div>
        <script src="../../static/assets/layui.js"></script>
        <script src="../../static/index.js" data-main="home"></script>
            <script src="../../static/home.js"></script>
        </div>
</body>
</html>

templates/bussiness/orders_query.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>厂商</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
</head>
<body class="layui-view-body">
    <div class="layui-content">
    	<!--面包屑导航-->
    	<div class="mianb">
    		<div class="mblf layui-col-xs6 layui-col-md6">
    			 <i class="layui-icon">&#xe656;</i>
    			 <p>物流追踪管理 > <span>生产商</span></p>
    		</div>
    		<div class="mbrt layui-col-xs6 layui-col-md6">
    			<a href="/corderslist" class="layui-btn layui-btn-normal" id="yonghu">返回</a>
    		</div>
    	</div>
    	<!--面包屑导航-->
        <div class="layui-row">
            <div class="layui-card">
            	<div class="table-responsive">
			 		  <table class="layui-table" lay-skin="line" lay-size="lg" id="table">
						  <thead>
						    <tr>
                                <th>编号</th>
                                <th>订单名</th>
                                <th>时间</th>
                                <th>产地</th>
                                <th>联系人</th>
                                <th>电话</th>
                                <th>状态</th>
                                <th>操作</th>
						    </tr>
						  </thead>
						  <tbody>
						    <tr>
                                <td>{{ order.id }}</td>
                                <td>{{ order.o_name }}</td>
                                <td>{{ order.o_time }}</td>
                                <td>{{ order.location }} </td>
                                <td>{{ order.person }} </td>
                                <td>{{ order.tel }}</td>
                                <td>{{ order.status }}</td>
                                <td>
                                <div class="layui-table-cell laytable-cell-1-0-10">
							      	  	<!--a class="layui-btn layui-btn-normal layui-btn-xs" href="{{url_for('bussiness_page.outc', id=order.id)}}">出厂</a-->
							      	  	<a class="layui-btn layui-btn-danger layui-btn-xs delete" href="{{url_for('login_page.show_detail', order_id=order.id)}}" >详情</a>
                                </div>
                                </td>
						    </tr>
						  </tbody>
					</table>
			 	</div>

           		<!--分页-->
           		<div id="page"></div>
           		<!--分页-->
            </div>
        </div>
    </div>
   	</div>
        <script src="../../static/assets/layui.js"></script>
        <script src="../../static/index.js" data-main="home"></script>
            <script src="../../static/home.js"></script>
        </div>
</body>
</html>

templates/bussiness/orderslist.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>厂商</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
    <link rel="stylesheet" href="../../static/bootstrap.min.css">
    <script src="../../static/jquery.min.js"></script>
    <script src="../../static/popper.min.js"></script>
    <script src="../../static/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../static/assets/css/navigation.css"/>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


</head>
<body class="layui-view-body">
<div class="container-fluid fixed-top bg-dark py-3" style="height:60px">
    <div class="row">
        <div class="col-sm-1 col-0 collapse show sidebar">
            <!-- spacer col -->
        </div>
        <div class="col px-3 col-sm-1">
            <!-- toggler -->
            <a data-toggle="collapse" href="#" data-target=".collapse" role="button">
                <i class="fa fa-bars fa-lg"></i>
            </a>
        </div>
    	    <div class="mianb col-sm-6">
    		    <div class="mblf layui-col-xs6 layui-col-md6">
    			     <i class="layui-icon">&#xe656;</i>
    			    <p>物流追踪管理 >生产商</p>
    		    </div>
                </div>
  <div class="dropdown col">
    <button type="button" class="btn btn-primary dropdown-toggle pull-right " data-toggle="dropdown"><i class="fa fa-gear"></i></button>
    <div class="dropdown-menu dropdown-menu-right" style="min-width: 100px">
      <a class="dropdown-item" href="{{ url_for('login_page.edit', id=user.id) }}">用户修改</a>
      <a class="dropdown-item" href="{{ url_for('login_page.exit') }}">退出</a>
    </div>
  </div>

    </div>
</div>


<div class="container-fluid">
    <div class="row vh-100 flex-nowrap">
        <div class="col-1 collapse show sidebar bg-dark text-white px-0">
            <ul class="nav flex-column flex-nowrap text-truncate navbar-dark bg-dark position-fixed pt-2 vh-100" id="sidebar">
                <li class="nav-item">
                    <a class="nav-link" href="#">订单管理</a>
                </li>
                <!--<li class="nav-item">-->
                    <!--<a class="nav-link disabled" href="#">Disabled</a>-->
                <!--</li>-->
            </ul>
        </div>



        <div class="layui-content col-sm-12">
            	    <div class="table-responsive">
	                        <table class="layui-table" lay-skin="line" lay-size="lg" id="table">
						      <thead>
						        <tr>
                                    <th>#</th>
                                    <th>编号</th>
                                    <th>订单名</th>
                                    <th>时间</th>
                                    <th>产地</th>
                                    <th>联系人</th>
                                    <th>电话</th>
                                    <th>状态</th>
                                    <th>操作</th>
						        </tr>
						    </thead>
						    <tbody>
                            {% for order in orders %}
						        <tr>
                                    <td>{{ loop.index + pagination.skip }}</td>
                                    <td>{{ order.id }}</td>
                                    <td>{{ order.o_name }}</td>
                                    <td>{{ order.o_time }}</td>
                                    <td>{{ order.location }} </td>
                                    <td>{{ order.person }} </td>
                                    <td>{{ order.tel }}</td>
                                    <td>{{ order.status }}</td>
                                    <td>
                                    <div class="layui-table-cell laytable-cell-1-0-10">
							      	      	<a class="layui-btn layui-btn-normal layui-btn-xs" href="{{url_for('bussiness_page.outc', id=order.id)}}">出厂</a>
							      	  	    <a class="layui-btn layui-btn-danger layui-btn-xs delete" href="{{url_for('login_page.show_detail', order_id=order.id)}}">详情</a>
                                    </div>
                                    </td>
						        </tr>
                            {% endfor %}

                            </tbody>
					    </table>
                        {{ pagination.info }}
                        <tr>
                            {{ pagination.links }}
                        </tr>
			 	    </div>



        <div class="mianb">
    		<div class="mbrt layui-col-xs6 layui-col-md6">
                 <form action="{{ url_for('bussiness_page.query', id=user.id) }}" method="post">
                <td>订单号: <input name="o_id" type="text" value=></td>
                <td><input type="submit" name="submit" value="查询" class="layui-btn layui-btn-normal"/></td>
                </form>
    		</div>
    		<div class="mbrt layui-col-xs6 layui-col-md6">
    			<a href="{{url_for('bussiness_page.add', id=user.id)}}" class="layui-btn layui-btn-normal" id="addbanner">新增订单</a>
    		</div>
    	</div>
        <script src="../../static/assets/layui.js"></script>
        <script src="../../static/index.js" data-main="home"></script>
            <script src="../../static/home.js"></script>
        </div>
         </div>
        </div>


</body>
</html>

templates/bussiness/outc.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>厂商</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
</head>
<body class="layui-view-body">
    <div class="layui-content">
    	<!--面包屑导航-->
    	<div class="mianb">
    		<div class="mblf layui-col-xs6 layui-col-md6">
    			 <i class="layui-icon">&#xe656;</i>
    			 <p>物流追踪管理 > <span>生产商</span></p>
    		</div>
    		<div class="mbrt layui-col-xs6 layui-col-md6">
    			<a href="/corderslist" class="layui-btn layui-btn-normal" >返回</a>
    		</div>
    	</div>
    	<!--面包屑导航-->
        <div class="layui-row">
            <div class="layui-card">
            	<div class="table-responsive">
                    <form action="{{ url_for('bussiness_page.outc', id=order.id) }}" method="post">
                        <table class="layui-table" lay-skin="line" lay-size="lg" id="table">
                            <tr><td>订单号：</td><td><input type="text" name="id" value="{{order.id}}" readonly="readonly"/></td></tr>
                            <tr><td>商品名：</td><td><input type="text" name="o_name" value="{{order.o_name}}" readonly="readonly"/></td>
                            <tr><td>生产时间：</td><td><input type="text" name="o_time" value="{{order.o_time}}"readonly="readonly"/></td>
                            <tr><td>状态：</td><td><input type="text" name="status" value="{{order.status}}" readonly="readonly"/></td>
                            <tr><td>仓库地址：</td><td><input type="text" name="desc" /></td>
                            <tr><td>仓库联系人：</td><td><input type="text" name="person" /></td>
                            <tr><td>仓库电话：</td><td><input type="text" name="tel" /></td>
                            <tr><td>&nbsp;</td><td><input type="submit" name="submit" value="出厂" class="layui-btn layui-btn-normal" /></td></tr>
                        </table>
                    </form>
			 	</div>

           		<!--分页-->
           		<div id="page"></div>
           		<!--分页-->
            </div>
        </div>
    </div>
    <font size="3" color="red" align="center">
    {% for message in get_flashed_messages() %}
        <p class="alert">{{ message }}</p>
    {% endfor %}
   	<div>
        <script src="../../static/assets/layui.js"></script>
        <script src="../../static/index.js" data-main="home"></script>
            <script src="../../static/home.js"></script>
        </div>

</body>
</html>