views/login.py
from flask import Blueprint, render_template, session, redirect, request, url_for, flash
from ..models import User, create_data, Orders
from ..extension import db

from ..blockchain import get_all_blocks
from werkzeug.security import check_password_hash, generate_password_hash


login_page = Blueprint('login_page', __name__)


@login_page.route('/login_page')
def users():
    id = session.get('user_id')
    if id:
        user = User.query.get(int(id))
        if user.types== "管理员":
            return redirect(url_for('admin_page.orders'))
        elif user.types == "厂商":
            return redirect(url_for('bussiness_page.list_all_orders'))
        elif user.types == "商家":
            return redirect(url_for('customer_page.list_all_orders'))
        elif user.types == "物流公司":
            return redirect(url_for('logistics_page.list_all_commodities'))
        elif user.types == "仓库":
            return redirect(url_for('warehouse_page.list_all_commodities'))
    else:
        return redirect('/')


@login_page.route('/')
@login_page.route('/login', methods=['GET', 'PoSt'])
def login():
    if request.method == 'GET':
        return render_template('login/login.html')
    else:
        name = request.form.get('name')
        pwd = request.form.get('password')
        if name == "" or pwd == "":
            flash('账号和密码不能为空')
            return render_template('login/login.html')

        user = User.query.filter(User.username == name).first()

        if user and check_password_hash(user.password, pwd):
            session['user_id'] = user.id
            return redirect(url_for('login_page.users'))
        else:
            flash('密码错误')
            return render_template('login/login.html')


@login_page.route('/addinitdata', methods=['GET', 'POST'])
def addinitdata():
    if request.method == 'POST':
        create_data()
        return render_template('login/login.html')


@login_page.route('/user_index/<id>', methods=['GET', 'POST'])
def edit(id):
    user = User.query.get(id)

    if request.method == 'GET':
        return render_template('login/edit.html',user=user)
    else:
        username = request.form.get('username')
        # old_password = request.form.get('old_password')
        # password = request.form.get('new_password')
        gender = request.form.get('gender')
        email = request.form.get('email')

        if not username or not gender or not email:
            flash("Invalid Input")
            return render_template('login/edit.html', user=user)

        user.username = username
        # user.password = generate_password_hash(password)
        user.gender = gender
        user.email = email
        db.session.commit()
        return redirect(url_for('login_page.users'))


@login_page.route('/user_password_index/<id>', methods=['GET', 'POST'])
def password_edit(id):
    user = User.query.get(id)

    if request.method == 'GET':
        return render_template('login/password_edit.html', user=user)
    else:
        # username = request.form.get('username')
        old_password = request.form.get('old_password')
        password = request.form.get('new_password')
        re_password = request.form.get('re_new_password')
        # gender = request.form.get('gender')
        # email = request.form.get('email')

        if not password == re_password:
            flash("新密码输入不同")
            return render_template('login/password_edit.html', user=user)

        if not check_password_hash(user.password, old_password):
            flash("原密码输入错误")
            return render_template('login/password_edit.html', user=user)
        
        # user.username = username
        user.password = generate_password_hash(password)
        # user.gender = gender
        # user.email = email
        db.session.commit()
        return redirect(url_for('login_page.users'))

@login_page.route('/exit', methods=['GET', 'POST'])
def exit():
    return render_template('login/login.html')

@login_page.route('/show_detail/<order_id>')
def show_detail(order_id):
    order = Orders.query.get(order_id)
    block_in_chain = get_all_blocks(order_id)
    if len(block_in_chain) != 0:
        block = block_in_chain[-1]
        message = block.history
        messages = message.split('\n')
        if messages[-1] == "":
            messages = messages[:-1]
    else:
        messages = ""
    return render_template('showdetail.html', order=order, messages=messages)

@login_page.route('/query',methods=['GET', 'POST'])
def query():
    o_id = request.form.get('o_id')
    order = Orders.query.filter(Orders.id==o_id).first()
    id = session.get('user_id')
    if id:
        user = User.query.get(int(id))
        if user.types == "商家":
            if order:
                if order.status == "已发货" or order.status == "已签收":
                    return render_template('customer/orders_query.html', orders=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")

        elif user.types == "物流公司":
            if order:
                if order.status == "已发货" or order.status == "已入仓":
                    return render_template('logistics/logistics_query.html', order=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")


        elif user.types == "仓库":
            if order:
                if order.status == "已出厂" or order.status == "已入仓":
                    return render_template('warehouse/warehouse_query.html', orders=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")

        #return render_template('orders_query.html', order=order)

templates/login/edit.html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>新增订单</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>

    <style>
    .alert {
    color: #AE1100;
      font-size: 20px;
      font-weight: bold;
      text-align: center;
      letter-spacing: 5px;
    }
    </style>

</head>
<body class="layui-view-body">
    <div class="layui-content">
    	<!--面包屑导航-->
    	<div class="mianb">
    		<div class="mblf layui-col-xs6 layui-col-md6">
    			 <i class="layui-icon">&#xe656;</i>
    			 <p>物流追踪管理 > <span>生产商</span></p>
    		</div>
    		<div class="mbrt layui-col-xs6 layui-col-md6">
    			<a href="{{url_for('login_page.users')}}" class="layui-btn layui-btn-normal" >返回</a>
    		</div>
    	</div>

        {% for message in get_flashed_messages() %}
        <p class="alert">{{ message }}</p>
        {% endfor %}

    	<!--面包屑导航-->
        <div class="layui-row">
            <div class="layui-card">
            	<div class="table-responsive">
                    <form action="{{ url_for('login_page.edit', id=user.id) }}" method="post">
                        <table class="layui-table" lay-skin="line" lay-size="lg" id="table">
                            <tr><td>用户名：</td><td><input id="name" type="text" name="username" value="{{ user.username }}"/></td></tr>
                            <tr><td>Email：</td><td><input id="email" type="text" name="email" value="{{ user.email }}"/></td></tr>
                            <tr><td>原密码：</td><td><input id="old_password" type="password" name="old_password"/></td></tr>
                            <tr><td>新密码：</td><td><input id="new_password" type="password" name="new_password"/></td></tr>
                            <tr><td>性别：</td>
                                <td>
                                    <input type="radio" name="gender" value="0" {% if user.gender == 0 %}checked {% endif %}/>男
                                    <input type="radio" name="gender" value="1" {% if user.gender == 1 %}checked {% endif %}/>女
                                </td></tr>
                            <tr><td> </td><td><input id="submit" type="submit" name="submit" value="修改"  class="layui-btn layui-btn-normal" /></td></tr>
                        </table>
                    </form>
			 	</div>

           		<!--分页-->
           		<div id="page"></div>
           		<!--分页-->
            </div>
        </div>
    </div>

</body>
</html>

templates/login/error_page.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>厂商</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
</head>
<body class="layui-view-body">
     {{message}}
    <ur class="sub">
        <li><a class="" href="{{url_for('login_page.users')}}">
        <span class="sub-menu-text">返回</span>></a>
        </li>
    </ur>

</body>
</html>

templates/login/login.html
<!DOCTYPE html>
<html>
<head>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}" type="text/css">

</head>
<body>

<form action="{{ url_for('login_page.login') }}" method="post">


  <div class="segment">

    <h1>Sign up</h1>
  </div>

  <label>
    <input type="text" placeholder="Username" name="name"/>

  </label>
  <label>
    <input type="password" placeholder="Password" name="password"/>
  </label>
  <button class="red" type="submit" name="submit"><i class="fa fa-lock"></i> Log in</button>
    {% for message in get_flashed_messages() %}
        <p class="alert">{{ message }}</p>
    {% endfor %}

</form>

<form action="{{ url_for('login_page.addinitdata') }}" method="post">
  <button class="data-input" type="submit" name="submit">导入数据</button>
</form>
</body>
</html>

templates/login/password_edit.html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>新增订单</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>

    <style>
    .alert {
    color: #AE1100;
      font-size: 20px;
      font-weight: bold;
      text-align: center;
      letter-spacing: 5px;
    }
    </style>

</head>
<body class="layui-view-body">
    <div class="layui-content">
    	<!--面包屑导航-->
    	<div class="mianb">
    		<div class="mblf layui-col-xs6 layui-col-md6">
    			 <i class="layui-icon">&#xe656;</i>
    			 <p>物流追踪管理 > <span>生产商</span></p>
    		</div>
    		<div class="mbrt layui-col-xs6 layui-col-md6">
    			<a href="{{url_for('login_page.users')}}" class="layui-btn layui-btn-normal" >返回</a>
    		</div>
    	</div>

        {% for message in get_flashed_messages() %}
        <p class="alert">{{ message }}</p>
        {% endfor %}

    	<!--面包屑导航-->
        <div class="layui-row">
            <div class="layui-card">
            	<div class="table-responsive">
                    <form action="{{ url_for('login_page.password_edit', id=user.id) }}" method="post">
                        <table class="layui-table" lay-skin="line" lay-size="lg" id="table">
                            <tr><td>用户名：</td><td><input id="name" type="text" name="username" value="{{ user.username }}" readonly/></td></tr>
                            <tr><td>Email：</td><td><input id="email" type="text" name="email" value="{{ user.email }}" readonly/></td></tr>
                            <tr><td>原密码：</td><td><input id="old_password" type="password" name="old_password"/></td></tr>
                            <tr><td>新密码：</td><td><input id="new_password" type="password" name="new_password"/></td></tr>
                            <tr><td>重复新密码：</td><td><input id="re_new_password" type="password" name="re_new_password"/></td></tr>
                            <tr><td>性别：</td>
                                <td>
                                    <input type="radio" name="gender" value="0" {% if user.gender == 0 %}checked {% endif %}/>男
                                    <input type="radio" name="gender" value="1" {% if user.gender == 1 %}checked {% endif %}/>女
                                </td></tr>
                            <tr><td> </td><td><input id="submit" type="submit" name="submit" value="修改"  class="layui-btn layui-btn-normal" /></td></tr>
                        </table>
                    </form>
			 	</div>

           		<!--分页-->
           		<div id="page"></div>
           		<!--分页-->
            </div>
        </div>
    </div>

</body>
</html>