views/login.py
from flask import Blueprint, render_template, session, redirect, request, url_for, flash
from ..models import User, create_data, Orders
from ..extension import db

from ..blockchain import get_all_blocks
from werkzeug.security import check_password_hash, generate_password_hash


login_page = Blueprint('login_page', __name__)


@login_page.route('/login_page')
def users():
    id = session.get('user_id')
    if id:
        user = User.query.get(int(id))
        if user.types== "管理员":
            return redirect(url_for('admin_page.orders'))
        elif user.types == "厂商":
            return redirect(url_for('bussiness_page.list_all_orders'))
        elif user.types == "商家":
            return redirect(url_for('customer_page.list_all_orders'))
        elif user.types == "物流公司":
            return redirect(url_for('logistics_page.list_all_commodities'))
        elif user.types == "仓库":
            return redirect(url_for('warehouse_page.list_all_commodities'))
    else:
        return redirect('/')


@login_page.route('/')
@login_page.route('/login', methods=['GET', 'PoSt'])
def login():
    if request.method == 'GET':
        return render_template('login/login.html')
    else:
        name = request.form.get('name')
        pwd = request.form.get('password')
        if name == "" or pwd == "":
            flash('账号和密码不能为空')
            return render_template('login/login.html')

        user = User.query.filter(User.username == name).first()

        if user and check_password_hash(user.password, pwd):
            session['user_id'] = user.id
            return redirect(url_for('login_page.users'))
        else:
            flash('密码错误')
            return render_template('login/login.html')


@login_page.route('/addinitdata', methods=['GET', 'POST'])
def addinitdata():
    if request.method == 'POST':
        create_data()
        return render_template('login/login.html')


@login_page.route('/user_index/<id>', methods=['GET', 'POST'])
def edit(id):
    user = User.query.get(id)

    if request.method == 'GET':
        return render_template('login/edit.html',user=user)
    else:
        username = request.form.get('username')
        # old_password = request.form.get('old_password')
        # password = request.form.get('new_password')
        gender = request.form.get('gender')
        email = request.form.get('email')

        if not username or not gender or not email:
            flash("Invalid Input")
            return render_template('login/edit.html', user=user)

        user.username = username
        # user.password = generate_password_hash(password)
        user.gender = gender
        user.email = email
        db.session.commit()
        return redirect(url_for('login_page.users'))


@login_page.route('/user_password_index/<id>', methods=['GET', 'POST'])
def password_edit(id):
    user = User.query.get(id)

    if request.method == 'GET':
        return render_template('login/password_edit.html', user=user)
    else:
        # username = request.form.get('username')
        old_password = request.form.get('old_password')
        password = request.form.get('new_password')
        re_password = request.form.get('re_new_password')
        # gender = request.form.get('gender')
        # email = request.form.get('email')

        if not password == re_password:
            flash("新密码输入不同")
            return render_template('login/password_edit.html', user=user)

        if not check_password_hash(user.password, old_password):
            flash("原密码输入错误")
            return render_template('login/password_edit.html', user=user)
        
        # user.username = username
        user.password = generate_password_hash(password)
        # user.gender = gender
        # user.email = email
        db.session.commit()
        return redirect(url_for('login_page.users'))

@login_page.route('/exit', methods=['GET', 'POST'])
def exit():
    return render_template('login/login.html')

@login_page.route('/show_detail/<order_id>')
def show_detail(order_id):
    order = Orders.query.get(order_id)
    block_in_chain = get_all_blocks(order_id)
    if len(block_in_chain) != 0:
        block = block_in_chain[-1]
        message = block.history
        messages = message.split('\n')
        if messages[-1] == "":
            messages = messages[:-1]
    else:
        messages = ""
    return render_template('showdetail.html', order=order, messages=messages)

@login_page.route('/query',methods=['GET', 'POST'])
def query():
    o_id = request.form.get('o_id')
    order = Orders.query.filter(Orders.id==o_id).first()
    id = session.get('user_id')
    if id:
        user = User.query.get(int(id))
        if user.types == "商家":
            if order:
                if order.status == "已发货" or order.status == "已签收":
                    return render_template('customer/orders_query.html', orders=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")

        elif user.types == "物流公司":
            if order:
                if order.status == "已发货" or order.status == "已入仓":
                    return render_template('logistics/logistics_query.html', order=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")


        elif user.types == "仓库":
            if order:
                if order.status == "已出厂" or order.status == "已入仓":
                    return render_template('warehouse/warehouse_query.html', orders=order)
                else:
                    return render_template('error_page.html', message="无权限查看")
            else:
                return render_template('error_page.html', message="查询结果不存在")

        #return render_template('orders_query.html', order=order)

templates/error_page.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>厂商</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
  <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<body class="layui-view-body">

  <div class="alert alert-danger alert-dismissible">
    <a type="submit" class="close" href="{{url_for('login_page.users')}}">&times;</a>
    <strong>失败!</strong> {{message}}。
  </div>


   	</div>
        <script src="../../static/assets/layui.js"></script>
        <script src="../../static/index.js" data-main="home"></script>
            <script src="../../static/home.js"></script>
        </div>
</body>
</html>

templates/orderslist.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{type}}</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
    <link rel="stylesheet" href="../../static/bootstrap.min.css">
    <script src="../../static/jquery.min.js"></script>
    <script src="../../static/popper.min.js"></script>
    <script src="../../static/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../static/assets/css/navigation.css"/>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


</head>
<body class="layui-view-body">
<div class="container-fluid fixed-top bg-dark py-3" style="height:60px">
    <div class="row">
        <div class="col-sm-1 col-0 collapse show sidebar">
            <!-- spacer col -->
        </div>
        <div class="col px-3 col-sm-1">
            <!-- toggler -->
            <a data-toggle="collapse" href="#" data-target=".collapse" role="button">
                <i class="fa fa-bars fa-lg"></i>
            </a>
        </div>
    	    <div class="mianb col-sm-6">
    		    <div class="mblf layui-col-xs6 layui-col-md6">
    			     <i class="layui-icon">&#xe656;</i>
    			    <p>物流追踪管理 >{{type}}</p>
    		    </div>
                </div>
  <div class="dropdown col">
    <button type="button" class="btn btn-primary dropdown-toggle pull-right " data-toggle="dropdown"><i class="fa fa-gear"></i></button>
    <div class="dropdown-menu dropdown-menu-right" style="min-width: 100px">
      <a class="dropdown-item" href="{{ url_for('login_page.edit', id=user.id) }}">用户修改</a>
      <a class="dropdown-item" href="{{ url_for('login_page.password_edit', id=user.id) }}">密码修改</a>
      <a class="dropdown-item" href="{{ url_for('login_page.exit') }}">退出</a>
    </div>
  </div>

    </div>
</div>


<div class="container-fluid">
    <div class="row vh-100 flex-nowrap">
        <div class="col-1 collapse show sidebar bg-dark text-white px-0">
            <ul class="nav flex-column flex-nowrap text-truncate navbar-dark bg-dark position-fixed pt-2 vh-100" id="sidebar">
                <li class="nav-item">
                        <a class="nav-link" href="#">订单管理</a>
                </li>
                <!--<li class="nav-item">-->
                    <!--<a class="nav-link disabled" href="#">Disabled</a>-->
                <!--</li>-->
            </ul>
        </div>



        <div class="layui-content col-sm-12">
            	    <div class="table-responsive">
	                        <table class="layui-table" lay-skin="line" lay-size="lg" id="table">
						      <thead>
						        <tr>
                                    <th>编号</th>
                                    <th>订单名</th>
                                    <th>时间</th>
                                    <th>当前地</th>
                                    {% if type != '仓库'%}<th>目的地</th>{%endif%}
                                    {% if type != '仓库'%}<th>联系人</th>{%endif%}
                                    {% if type != '仓库'%}<th>电话</th> {%endif%}
                                    {% if type == '物流公司' or type =="商家" %}<th>物流公司</th> {%endif%}
                                    {% if type == '物流公司' or type =="商家" %}<th>物流单号</th> {%endif%}

                                    <th>状态</th>
                                    <th>操作</th>
						        </tr>
						    </thead>
						    <tbody>
                            {% for order in orders %}
						        <tr>
                                    <td>{{ order.id }}</td>
                                    <td>{{ order.o_name }}</td>
                                    <td>{{ order.o_time }}</td>
                                    <td>{{ order.location }} </td>
                                    {% if type != '仓库'%}<td>{{ order.desc }} </td>{%endif%}
                                    {% if type != '仓库'%}<td>{{ order.person }} </td>{%endif%}
                                    {% if type != '仓库'%}<td>{{ order.tel }}</td>{%endif%}
                                    {% if type == '物流公司' or type == "商家" %}<td>{{order.comp}}</td> {%endif%}
                                    {% if type == '物流公司' or type == "商家" %}<td>{{order.comp_id}}</td> {%endif%}


                                    <td>{{ order.status }}</td>
                                    <td>
                                    <div class="layui-table-cell laytable-cell-1-0-10">
							      	      	<a class="layui-btn layui-btn-normal layui-btn-xs" href="{{url_for(hre, id=order.id)}}">{{ops}}</a>
							      	  	    <a class="layui-btn layui-btn-danger layui-btn-xs delete" href="{{url_for('login_page.show_detail', order_id=order.id)}}">详情</a>
                                    </div>
                                    </td>
						        </tr>
                            {% endfor %}

                            </tbody>
					    </table>
                        {{ pagination.info }}
                        <tr>
                            {{ pagination.links }}
                        </tr>
			 	    </div>



        <div class="mianb">
    		<div class="mbrt layui-col-xs6 layui-col-md6">
                 <form action="{{ url_for('login_page.query') }}" method="post">
                     <tr>
                        <td>订单编号: <input name="o_id" type="text" value=></td>
                        <td><input type="submit" name="submit" value="查询" class="layui-btn layui-btn-normal"/></td>
                     </tr>
                </form>
    		</div>
    	</div>
        <script src="../../static/assets/layui.js"></script>
        <script src="../../static/index.js" data-main="home"></script>
            <script src="../../static/home.js"></script>
        </div>
         </div>
        </div>


</body>
</html>

templates/showdetail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>厂商</title>
    <link rel="stylesheet" href="../../static/assets/css/layui.css">
    <link rel="stylesheet" href="../../static/assets/css/view.css"/>
    <link rel="stylesheet" href="../../static/assets/css/admin.css"/>
    <script src="../static/jquery.min.js" type="text/javascript"></script>

</head>
<body class="layui-view-body">
    <div class="layui-content">
    	<!--面包屑导航-->
    	<div class="mianb">
    		<div class="mblf layui-col-xs6 layui-col-md6">
    			 <i class="layui-icon">&#xe656;</i>
    			 <p>物流追踪管理 > <span></span></p>
    		</div>
    		<div class="mbrt layui-col-xs6 layui-col-md6">
    			<a href="{{url_for('login_page.users')}}" class="layui-btn layui-btn-normal" id="yonghu">返回</a>
    		</div>
    	</div>
    	<!--面包屑导航-->
         <!--lay-size="lg"-->
        <div class="layui-row">
            <div class="layui-card">

            	<div class="table-responsive">
                    <div align="center">
                        <img id='img' height="200" width="200" src="{{order.qrcode}}"/>
                    </div>
			 		  <table class="layui-table" lay-skin="line" id="table">
						    <!--tr>
                                <td>二维码</td>
                                    <td><img id='img' height="200" width="250" src="{{order.qrcode}}"/></td>
						        </tr-->
                            {% for message in messages %}
						    <tr>
                                <td>区块信息</td>
                                <td>{{message}}</td>
						    </tr>
                            {% endfor %}
					</table>
			 	</div>

           		<!--分页-->
           		<div id="page"></div>
           		<!--分页-->
            </div>
        </div>
    </div>
   	</div>
        <script src="../../static/assets/layui.js"></script>
        <script src="../../static/index.js" data-main="home"></script>
        <script src="../../static/home.js"></script>

    </div>
</body>
</html>